// <auto-generated />
using System;
using ELLPScore.Context.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ELLPScore.Migrations
{
    [DbContext(typeof(ELLPScoreDBContext))]
    partial class ELLPScoreDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ELLPScore.Domain.Aluno", b =>
                {
                    b.Property<int>("AlunoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlunoID"));

                    b.Property<string>("Anotacoes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Turma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AlunoID");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("ELLPScore.Domain.AlunoDisciplina", b =>
                {
                    b.Property<int>("AlunoID")
                        .HasColumnType("int");

                    b.Property<int>("DisciplinaID")
                        .HasColumnType("int");

                    b.HasKey("AlunoID", "DisciplinaID");

                    b.HasIndex("DisciplinaID");

                    b.ToTable("AlunoDisciplinas");
                });

            modelBuilder.Entity("ELLPScore.Domain.Disciplina", b =>
                {
                    b.Property<int>("DisciplinaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DisciplinaID"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("DisciplinaID");

                    b.ToTable("Disciplinas");
                });

            modelBuilder.Entity("ELLPScore.Domain.Feedback", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("AlunoID")
                        .HasColumnType("int");

                    b.Property<int?>("ProfessorID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AlunoID");

                    b.HasIndex("ProfessorID");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("ELLPScore.Domain.Nota", b =>
                {
                    b.Property<int>("NotaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotaID"));

                    b.Property<int?>("AlunoID")
                        .HasColumnType("int");

                    b.Property<int?>("DisciplinaID")
                        .HasColumnType("int");

                    b.Property<decimal>("NotaValor")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("TurmaID")
                        .HasColumnType("int");

                    b.HasKey("NotaID");

                    b.HasIndex("AlunoID");

                    b.HasIndex("DisciplinaID");

                    b.HasIndex("TurmaID");

                    b.ToTable("Notas");
                });

            modelBuilder.Entity("ELLPScore.Domain.Professor", b =>
                {
                    b.Property<int>("ProfessorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfessorID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProfessorID");

                    b.ToTable("Professores");
                });

            modelBuilder.Entity("ELLPScore.Domain.Turma", b =>
                {
                    b.Property<int>("TurmaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TurmaID"));

                    b.Property<string>("CodigoOuNome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ProfessorID")
                        .HasColumnType("int");

                    b.HasKey("TurmaID");

                    b.HasIndex("ProfessorID");

                    b.ToTable("Turmas");
                });

            modelBuilder.Entity("ELLPScore.Domain.TurmaAluno", b =>
                {
                    b.Property<int>("TurmaID")
                        .HasColumnType("int");

                    b.Property<int>("AlunoID")
                        .HasColumnType("int");

                    b.HasKey("TurmaID", "AlunoID");

                    b.HasIndex("AlunoID");

                    b.ToTable("TurmaAlunos");
                });

            modelBuilder.Entity("ELLPScore.Domain.TurmaDisciplina", b =>
                {
                    b.Property<int>("TurmaID")
                        .HasColumnType("int");

                    b.Property<int>("DisciplinaID")
                        .HasColumnType("int");

                    b.HasKey("TurmaID", "DisciplinaID");

                    b.HasIndex("DisciplinaID");

                    b.ToTable("TurmaDisciplinas");
                });

            modelBuilder.Entity("ELLPScore.Domain.AlunoDisciplina", b =>
                {
                    b.HasOne("ELLPScore.Domain.Aluno", "Aluno")
                        .WithMany("AlunoDisciplinas")
                        .HasForeignKey("AlunoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ELLPScore.Domain.Disciplina", "Disciplina")
                        .WithMany("AlunoDisciplinas")
                        .HasForeignKey("DisciplinaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Disciplina");
                });

            modelBuilder.Entity("ELLPScore.Domain.Feedback", b =>
                {
                    b.HasOne("ELLPScore.Domain.Aluno", "Aluno")
                        .WithMany("Feedbacks")
                        .HasForeignKey("AlunoID");

                    b.HasOne("ELLPScore.Domain.Professor", "Professor")
                        .WithMany("Feedbacks")
                        .HasForeignKey("ProfessorID");

                    b.Navigation("Aluno");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("ELLPScore.Domain.Nota", b =>
                {
                    b.HasOne("ELLPScore.Domain.Aluno", "Aluno")
                        .WithMany("Notas")
                        .HasForeignKey("AlunoID");

                    b.HasOne("ELLPScore.Domain.Disciplina", "Disciplina")
                        .WithMany("Notas")
                        .HasForeignKey("DisciplinaID");

                    b.HasOne("ELLPScore.Domain.Turma", "Turma")
                        .WithMany("Notas")
                        .HasForeignKey("TurmaID");

                    b.Navigation("Aluno");

                    b.Navigation("Disciplina");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("ELLPScore.Domain.Turma", b =>
                {
                    b.HasOne("ELLPScore.Domain.Professor", "Professor")
                        .WithMany("Turmas")
                        .HasForeignKey("ProfessorID");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("ELLPScore.Domain.TurmaAluno", b =>
                {
                    b.HasOne("ELLPScore.Domain.Aluno", "Aluno")
                        .WithMany("TurmaAlunos")
                        .HasForeignKey("AlunoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ELLPScore.Domain.Turma", "Turma")
                        .WithMany("TurmaAlunos")
                        .HasForeignKey("TurmaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("ELLPScore.Domain.TurmaDisciplina", b =>
                {
                    b.HasOne("ELLPScore.Domain.Disciplina", "Disciplina")
                        .WithMany("TurmaDisciplinas")
                        .HasForeignKey("DisciplinaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ELLPScore.Domain.Turma", "Turma")
                        .WithMany("TurmaDisciplinas")
                        .HasForeignKey("TurmaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disciplina");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("ELLPScore.Domain.Aluno", b =>
                {
                    b.Navigation("AlunoDisciplinas");

                    b.Navigation("Feedbacks");

                    b.Navigation("Notas");

                    b.Navigation("TurmaAlunos");
                });

            modelBuilder.Entity("ELLPScore.Domain.Disciplina", b =>
                {
                    b.Navigation("AlunoDisciplinas");

                    b.Navigation("Notas");

                    b.Navigation("TurmaDisciplinas");
                });

            modelBuilder.Entity("ELLPScore.Domain.Professor", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Turmas");
                });

            modelBuilder.Entity("ELLPScore.Domain.Turma", b =>
                {
                    b.Navigation("Notas");

                    b.Navigation("TurmaAlunos");

                    b.Navigation("TurmaDisciplinas");
                });
#pragma warning restore 612, 618
        }
    }
}
